fixes #4926 if found under /etc/asterisk then move it unless it was specically suppose to be there, needs testing
git-svn-id: http://svn.freepbx.org/freepbx/branches/2.9@11719 05cd7311-dd0d-0410-8c4e-c7a75d82e046

diff --git a/amp_conf/bin/freepbx_engine b/amp_conf/bin/freepbx_engine
--- a/amp_conf/bin/freepbx_engine
+++ b/amp_conf/bin/freepbx_engine
@@ -10,12 +10,28 @@ ux="\e[0m"
 
 ROOT_UID=0	 # root uid is 0
 E_NOTROOT=67 # Non-root exit error
+
+# function to eventually get freepbx.conf to /etc
+move_freepbxconf() {
+	if [ -e /etc/asterisk/freepbx.conf -a ! -e /etc/freepbx.conf ]; then
+		echo moving /etc/asterisk/freepbx.conf to /etc/freepbx.conf
+		mv /etc/asterisk/freepbx.conf /etc/
+  	if [ "$?" -ne "0" ]; then
+			echo "unable to move, FreePBX will function fine but you will"
+			echo "get this error until the file can be successfully moved"
+		else
+			FREEPBX_CONF="/etc/freepbx.conf"
+  	fi
+	fi
+}
+
 # define freepbx config file if not already set
 if [ -z "$FREEPBX_CONF" ]; then
 	if [ -e "/etc/freepbx.conf" ]; then
 		FREEPBX_CONF="/etc/freepbx.conf"
 	elif [ -e "/etc/asterisk/freepbx.conf" ]; then
 		FREEPBX_CONF="/etc/asterisk/freepbx.conf"
+		move_freepbxconf
 	else
 		FREEPBX_CONF="/etc/freepbx.conf"
 	fi
@@ -29,7 +45,6 @@ then
 	echo
 	exit $E_NOTROOT
 fi
-
 
 # Set some defaults which can be re-defined from the config file/db
 AMPDEVUSER=asterisk
@@ -58,14 +73,6 @@ write_freepbxconf() {
 		require_once('${AMPWEBROOT}/admin/bootstrap.php');
 
 		EOF
-	fi
-	if [ -e /etc/asterisk/freepbx.conf -a ! -e /etc/freepbx.conf ]; then
-		echo moving /etc/asterisk/freepbx.conf to /etc/freepbx.conf
-		mv /etc/asterisk/freepbx.conf /etc/
-  	if [ "$?" -ne "0" ]; then
-			echo "unable to move, FreePBX will function fine but you will"
-			echo "get this error until the file can be successfully moved"
-  	fi
 	fi
 }
 
