change rm to mv and don't call write_freepbxconf every time we run restart. (if this is desired, then it should be called from start more so then restart (but both) re #4838 not closing until tested and feedback provided
git-svn-id: http://svn.freepbx.org/freepbx/branches/2.9@11493 05cd7311-dd0d-0410-8c4e-c7a75d82e046

diff --git a/amp_conf/bin/freepbx_engine b/amp_conf/bin/freepbx_engine
--- a/amp_conf/bin/freepbx_engine
+++ b/amp_conf/bin/freepbx_engine
@@ -10,7 +10,7 @@ ux="\e[0m"
 
 ROOT_UID=0	 # root uid is 0
 E_NOTROOT=67 # Non-root exit error
-# define freepbx config file if not alreaddy set
+# define freepbx config file if not already set
 if [ -z "$FREEPBX_CONF" ]; then
 	if [ -e "/etc/freepbx.conf" ]; then
 		FREEPBX_CONF="/etc/freepbx.conf"
@@ -59,8 +59,13 @@ write_freepbxconf() {
 
 		EOF
 	fi
-	if [ -e /etc/asterisk/freepbx.conf ]; then
-		rm /etc/asterisk/freepbx.conf
+	if [ -e /etc/asterisk/freepbx.conf -a ! -e /etc/freepbx.conf ]; then
+		echo moving /etc/asterisk/freepbx.conf to /etc/freepbx.conf
+		mv /etc/asterisk/freepbx.conf /etc/
+  	if [ "$?" -ne "0" ]; then
+			echo "unable to move, FreePBX will function fine but you will"
+			echo "get this error until the file can be successfully moved"
+  	fi
 	fi
 }
 
@@ -375,7 +380,6 @@ case "$1" in
 		stop_asterisk
 		stop_fop
 		sleep 1
-		write_freepbxconf
 		chown_asterisk
 		run_asterisk
 		if [ -z "$FOPRUN" -o "$FOPRUN" == "true" -o "$FOPRUN" == "TRUE" -o "$FOPRUN" == "True" -o "$FOPRUN" == "yes" -o "$FOPRUN" == "YES" -o "$FOPRUN" == "Yes" ]
